### ISSUE TITLE
MSU shuffler: randomly pick tracks from all installed MSU packs

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#112]

**Comment by MattEqualsCoder** [comment]
So wanted to bring this one up as I created that other MSU shuffler script, and I'm planning on making it into a standalone app. Thinking into it more, I feel like it probably makes more sense not to have this functionality bundled into the SMZ3 codebase due the fact that some people might actually want to use it for ALttPR runs (I think both Pink and skelebro have mentioned being interested in this).

That being said, I can look into adding functionality for SMZ3 to call out to the MSU shuffler app I create? That, or I can look into trying to make the core functionality into a library that the SMZ3 codebase can call out to.

**Comment by Vivelin** [comment]
A shared library might be the best solution; then we can have a generic script for multiple games and the ability to more easily and properly integrate it in SMZ3 at a later date.
