### ISSUE TITLE
Tracker does not work with races

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#144]
We need to make sure that when in race mode, tracker does the following:
- Rerolls the seed before generating the world
- Disable hints/spoilers
- Not correct you when you mark or track an incorrect item at a location
- Not auto track items for when marking Z3 bosses as defeated

**Comment by Vivelin** [comment]
What's the point of rerolling the seed?

The other items should honestly be part of hints/spoilers instead of just race mode.

**Comment by MattEqualsCoder** [comment]
So rerolling the seed is maybe not the best way of putting this. But on line 62 of Smz3Randomizer.cs, you'll see that if it's set to Race mode, it'll replace the seed number with a new random number. My best guess is since it outputs a slightly abbreviated spoiler log (which still spoils everything if you look at it?), this is done so people can't just generate the seed normally and get the full spoiler log which shows the spheres. Problem is that tracker seemingly doesn't keep track of this value so it uses the original seed number, not the rerolled one and will have a different set of items.

For your second point, I'm guessing you mean to not have tracker correct you or track items for defeated bosses unless spoilers/hints are enabled? That way we can disable hints/spoilers for race seeds, and it covers everything?

**Comment by Vivelin** [comment]
Okay, understood. If tracker doesn't work properly at all with Race enabled, that's a bug we should fix for sure.

Second point: correct, at least on the "correct you" part. As for tracking boss items, I'm not 100% sure. I guess tracking the boss and then the item separately is probably fine too.
