### ISSUE TITLE
Favorite & Randomize sprites and MSU packs

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#164]
There's more and more sprites and MSU packs coming out and the list keeps getting larger and larger.

Being able to mark sprites and packs as favorites and being able to select "Random" or "Random favorite" for each would be a fantastic addition.

Notes:
- [x] The "Random" or "Random favorite" option should be saved so you don't have to re-select "random" every time.
- [x] Selecting "Random" shouldn't have Tracker use "Random" as the character's name in hints.
- [x] Bonus points if you prevent rolling the same option too often (whether using weights or otherwise)

**Comment by MattEqualsCoder** [comment]
In regards to this, I know you started doing the MSU manager, but I think at least maybe scanning an MSU folder or maybe just saving previous MSUs you used and creating a dropdown to pick them would be nice.

**Comment by TheRealFragger** [comment]
I think rolling this into the Sprite Preview is a good idea too. Scrolling through the LTTP sprites is a bit of a nightmare. I think putting something in the options about how it shows sprites in the pull down selection would be a good idea too with the options being All, Favorite Priority (favorites at the top) and Favorites Only.
