### ISSUE TITLE
Redo reward system

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#177]
It's been known for a long time now that the way that rewards are setup is kinda annoying since they are handled entirely differently from other logic checks, but DigitalBasic ran into an actual issue caused by it on their Friday night keysanity stream.

Effectively, it was previously known that locations accessible via rewards like Sahasrahla, lumberjack tree, etc. were shown as accessible in Tracker. I was able to compensate for this a bit with some pretty gross logic in the TrackerSyncer. However, it appears the reverse can also be true. For example, if someone were to go out of logic and beat the green pendant dungeon by going out of logic, Sahasrahla will never show as in logic. I think this theoretically could apply to Ganon's Tower if one of the crystal dungeons is beaten out of logic and is probably why GT can be so fussy about complaining about being out of logic for folks like Pink.

I think either we could move the Rewards to be items that are then accessed via the Progression class like everything else. Or, we could change Rewards to be their own set of collectable objects that are used.

**Comment by Vivelin** [comment]
I think it makes sense to treat them as any other item.
