### ISSUE TITLE
Prevent repeated out of logic messages

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#178]
Currently Tracker will give out of logic messages for nearly every item over and over, which can be annoying in places like GT with lots of chests back to back. Definitely funny at first, but probably best to try to minimize this.

Perhaps if two back-to-back out of logic locations are missing the same set of items and are in the same region, the sass should be skipped?

**Comment by Vivelin** [comment]
Yeah, that might be a good idea. Maybe a separate set for repeated sass that just says nothing most of the time with a very low chance for some extra lines.

Requiring two sets of power bombs and only having one (or more generally, an item is missing that you already have, indicating it requires multiple) probably shouldn't have any sass to begin with, or a separate set of sass ("_Are you sure you have enough power bombs left now?_" or "_You don't want to repeat the Crocomire incident do you?_").

**Comment by Vivelin** [comment]
@MattEqualsCoder This is resolved with 6.0, right?

**Comment by MattEqualsCoder** [comment]
Not yet. GT should be taken care of as it has an empty string for its out of logic messages. But there is no global check to see if one out of logic location has the same set of missing items as the next.
