### ISSUE TITLE
Split keysanity in multiple options

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#179]
Currently keysanity is either off or on. Introduce options to have keysanity enabled for one game or the other. I originally came up with the idea so that people could play with the SM keys to potentially balance the two games a bit more and require people to go back and forth rather than the vast majority of seeds almost ending up with you doing 75% of SM in one go.

**Comment by Vivelin** [comment]
Yeah, this sounds fun. 

We should experiment a bit with placement of the keys. If all the keycards end up in Super Metroid, it just makes it more tedious, so maybe we could have an option for it. 

For example, we could force all keycards in ALttP (or maybe place them in dungeons to make it more predictable?). Considering keysanity is optional we don't have to be _too_ careful with the seed length but I'd prefer it to stay fun instead of tedious.

**Comment by MattEqualsCoder** [comment]
So this is pretty much implemented. In regards to your point about experimenting, I added an option to tweak the placement of progression items. I figured it might be fun to have them in general to offer little twists.

![image](https://user-images.githubusercontent.com/63823784/185826401-061eecac-e836-4119-a153-a9ec9372964c.png)

I will say that with some of these settings, things are a bit less stable in the sense that it's not able to generate fully solvable seeds and does the pop up warning. Should I maybe see how easy it is to try to roll the seed 5 times or something before giving up?

**Comment by Vivelin** [comment]
Hmm... I think we might have better luck just re-working the filling algorithm, honestly. I'm not confident it's actually impossible to generate a seed that way.

For now, though... if you think that'll help? But that'll have to be a pretty temporary solutions.

**Comment by MattEqualsCoder** [comment]
I do think it would help. I tested with some stats, and here are some percentages of how often it was able to successfully generate a seed:

None / Anywhere -> 100% success
None / Dungeons+Metroid -> 99% success
None / Crystal+Metroid -> 47% success
None / Opposite Game -> 78% success
None / Same Game -> 88% success

Both / Anywhere -> 99% success
Both / Dungeons+Metroid -> 84% success
Both / Crystal+Metroid -> 18% success
Both / Opposite Game -> 56% success
Both / Same Game -> 42% success

That's basically best and worst scenarios.

My best guess for what's happening based on my understanding of the logic and generation is that it's not exactly smart. It's mostly completely random in the order of items it places and where it will try to place them. It basically goes "Hey, I'm trying to place X, so where can I go without X?" It does this in a reverse order. So if items that don't really open up much happen to be in the bottom of the list, it's more likely to get stuck.

For example, lets say we've selected the crystals + Metroid, and we'll even assume Eastern is a crystal. But, if gravity suit + moon pearl + hook shot + silver arrows are near the bottom. Those don't really open anything up. This causes 

And, honestly, I don't know if I have a great solution. For multiworld, it item biases to moon pearls and morphs to appear earlier on to help open up things faster. We may want to consider doing the same here to try to help avoid these scenarios. I might try to look at the current ALttPR to see how its generation is, but I would imagine it's mostly the same unless they've majorly changed it over the last few years. If it is, I doubt if I'd be able to come up with a better method than what everyone else has collectively put together over the years.

So, in the end, the "best" options may be to make a handful of items that are likely to open up more locations quickly biased toward the bottom (we could possibly even have a larger list and randomly pick like 2-3), do like 5 attempts to generate a seed, and maybe even make a note that some of these progression item placement options may have a harder time generating and the early game may be a bit more samey than having things fully open. But I think that's fine as these are meant to be just little twists on the formula.

**Comment by MattEqualsCoder** [comment]
So thinking on it, another possibility could be that basically sphere 1 is fair game for anything no matter what setting. Again, we would probably want a warning, but that could hopefully populate more of a starting set of items to lower the chances of dead ends when generating the seed.

**Comment by Vivelin** [comment]
I wonder if we could do some hacky form of A/B testing and simply try both and see which results in better seeds.

**Comment by MattEqualsCoder** [comment]
I can try to do something, though obviously it can be a bit hard to tell what would be most fun just by just reading the spoiler log. I do think there are a few sort of goals we can have. 

- Obviously it should have a higher chance of success. I think the rerolling multiple times is good and can help in other situations. I know Pink has to reroll sometimes because it doesn't like boots being at sanctuary, for example. But with as low as 18% chance, even 5 rerolls is not unlikely to provide an error. I think even with rerolls, we should aim for at least a 50% success rate, though obviously higher is better.
- I noticed during some of my stats checking the morph ball got to be in a really low number of places (I want to say one of the options was as low as 8, but I definitely know it dropped down to 11). I'd want progression items to always have at least 30 different unique locations. When I rolled 100 seeds on all defaults, the morph ball had 69 (nice) unique locations for comparison. No keysanity with crystal + metroid resulted in 20 unique morph ball locations.
- I think we should aim for a max average number of spheres. No clue what that amount should be, though. I'd have to see what default SMZ3 and default full keysanity are first.

**Comment by MattEqualsCoder** [comment]
Okay, so from some testing, it seemed like tweaking the bias of items really changed a whole lot without doing multiple, and I'd worry about that making seeds too consistent.

However, making sphere one fair game no matter what item placement setting seemed to solve pretty much all problems. When running every combination of keysanity mode and item placement mode 1000 times each, things are looking good. All combinations seem to have over a 95% success rate in generating. None of them have crazy high sphere counts (for most it's the opposite because of fewer places to check). The item with the lowest amount of unique locations (usually morph bomb) is pretty decent, with the lowest being 47 with the "progression is in the vanilla game" option, and that makes sense. There's only so many locations the morph ball can be in SM. So when it comes to the item placement stuff, I'm pretty happy with it. I think they'll make for interesting little twists on the normal formula.

When it comes to the keysanity options though, I think you were right in the end to make your suggestion about experimenting with the item placement stuff. Metroid only keysanity does definitely increase the average sphere count (from an average of 14.4 spheres for regular SMZ3, 15.8 for regular keysanity, 12.3 for Zelda only keysanity, to 18.1 for Metroid only keysanity). Crystal Dungeons + Metroid lower it down to 16.6. Now, what does this mean for fun factor? Honestly I have no clue. I think what we might just need to do is release it as is, mention we're not sure exactly how it'll feel, and just let people experiment. We can always make changes later. It also doesn't look like it'll be too awfully hard to split the Metroid 

So, unless you have any concerns, I'll probably get this finished up and try to create a PR in the next day or two. I still want to add in the multiple attempts since I know Pink at least runs into the issue with boots in sanc. I think it'll probably have some conflicts with your PR though, so I don't mind waiting to merge this in until yours gets finished up so I can address those conflicts in my branch.

**Comment by Vivelin** [comment]
I don't know if sphere count necessarily means much. Considering most people who play Keysanity will use skips, it's probably not as bad. I'm all for more options, especially if it'll let people experiment. 

I suggest removing options that end up not being used after a while. I'm not sure if we need to start gathering telemetry for that or something, or if asking in Discord with a poll or something will be enough.

As for my own PR, I'm hoping I might have time to finish up today. It won't be perfect yet, but hopefully enough to have decent plando support to be fun.
