### ISSUE TITLE
Auto count GT items

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#191]
With auto tracking, it should be able to be possible to count the items automatically and announce what number the GT item was. Special care will need to be done with the torch item as it should be incremented upon entering that room for the first time, but _not_ incremented upon picking up the item.

If this is implemented, it would be nice to disable normal item messages while in GT and replace it with tracker just saying the number.

**Comment by Vivelin** [comment]
👍
