### ISSUE TITLE
Request to make pull request

### ISSUE THREAD

**Issue by fxbx** [Vivelin/SMZ3Randomizer#211]
I have 3 edited files to forward for consideration:

src\Randomizer.Shared\Models\LogicConfig.cs
Consistency in tooltips (periods on end of all) and second "gravity suit" edited to Waterway in Pink Brinstar

src\Randomizer.SMZ3.Tracking\AutoTracking\LuaConnector.cs
Mod to conditional in the event that Lua was not connected to: I was getting "A blocking operation was interrupted by a call to WSACancelBlockingCall." in my logs if I closed tracker without connecting. I owe it a bit of testing.

src\Randomizer.SMZ3.Tracking\Tracker.cs
Mod to check if any microphone devices exist before attempting to connect and then receiving exception. It uses an extern so if that isn't acceptable, it looks like the Exception will have to be.
Ref:
https://stackoverflow.com/questions/22734731/no-microphone-speechrecognitionengine-setinputtodefaultaudiodevice-problems
~
In the latest release I wasn't getting any tracker voice feedback so I cloned and built everything, glad it was very easy. That solved it but not sure yet what the issue was.

**Comment by Vivelin** [comment]
I don't know when I'll be able to test your changes but feel free to start a PR and I'll take a look when I'm able.

**Comment by fxbx** [comment]
GitHub Desktop won't let me publish my branch, and the New Pull Request button takes me to https://github.com/Vivelin/SMZ3Randomizer/compare

I might be doing something wrong here though.

**Comment by Vivelin** [comment]
Yeah, only contributors can create branches directly. You can create a PR if you fork the repository first. GitHub can do this for you automatically if you edit files through the site itself.

**Comment by fxbx** [comment]
I see now, thank you. Used site, 3 separate.

**Comment by Vivelin** [comment]
Thank you for your changes, they've been merged. I'm curious though, how did you find this?

**Comment by fxbx** [comment]
I was looking into the issue I had in the new release getting the tracker to speak at all, checking logging and I found the two stack traces. Harmless events for sure but avoidable exceptions.

I installed an old version and speech still wasn't active there, so I anticipate it's my env: eventually I'll try to solve that mystery.
