### ISSUE TITLE
Reminder to equip plasma beam

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#222]
Have Tracker remind players to equip Plasma Beam when entering Metroid if they acquired it in Zelda

**Comment by Vivelin** [comment]
Is it only plasma that doesn't auto-equip? If so, trying to do it automatically makes more ense.

**Comment by MattEqualsCoder** [comment]
It can happen with spazer at least. Not sure about the others.

**Comment by MattEqualsCoder** [comment]
I think there's a chance I can auto-enable it when transitioning between games in the assembly.
