### ISSUE TITLE
Add Additional QoL Patches

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#228]
We should make it easier to add additional QoL Patches and add some extras from VARIA and other places.

Here are some possibilities we should look at for some to add for Super Metroid at least:
- Aim any button (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/AimAnyButton.ips)
- Nerfed default charge beam (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/nerfed_charge.ips)
- Save stations refill (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/refill_before_save.ips)
- Fast Doors (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/fast_doors.ips)
- Fast Elevators (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/elevators_speed.ips)
- Speed Keep (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/rando_speed.ips)
- Colorblind friendly doors (https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/ips/color_blind.ips)

**Comment by Vivelin** [comment]
It might be good to see if we can find the original .asm source for these on metroidconstruction.com.

**Comment by Vivelin** [comment]
- Aim anything (Kejardon): https://metroidconstruction.com/resource.php?id=234
- Nerfed default charge beam (Smiley/Flo): https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/src/nerfed_charge.asm
- Save stations refill (adamf): https://metroidconstruction.com/resource.php?id=19
- Fast Doors (kazuto): https://github.com/theonlydude/RandomMetroidSolver/blob/master/patches/common/src/fast_doors.asm
- Fast Elevators (Lioran): https://metroidconstruction.com/resource.php?id=104
- Speed Keep (Scyzer and others): https://metroidconstruction.com/resource.php?id=368
- Colorblind friendly doors (?): ?

**Comment by Vivelin** [comment]
Other patches we talked about that would fit the same theme:

Symmetrical green gate glitch (Oi27): https://metroidconstruction.com/resource.php?id=572

Fix Bomb Torizo trigger (P.JBoy): https://metroidconstruction.com/resource.php?id=491

+ Whatever else we mentioned on Discord

**Comment by MattEqualsCoder** [comment]
So the colorblind friendly doors didn't seem to work well for SMZ3 unfortunately, but all of the other original ips patches I was able to get integrated seemingly with no issues. Main one I'm still a bit concerned about is the fast doors one because of the transition between world. It seemed to work okay, but that may be something that may cause more subtle issues with transitioning games that aren't easy to immediately see.

For the last two posted ASM patches, I'll need to see if I can figure out how to get those added into the base patch. I don't think we'd really need options for those. Bozo would possibly be good to have it be an option, but I don't like the soft lock potential as is, and it's an easy fight anyway, so I think it's probably fine to make that change.
