### ISSUE TITLE
ROM validation

### ISSUE THREAD

**Issue by andOlga** [Vivelin/SMZ3Randomizer#248]
Currently, the application does nothing to confirm that the selected original ROMs are, in fact, Super Metroid/Link to the Past ROMs, or even that they are SNES ROMs in any way at all (you can even just feed it two blank files). When generating a randomized ROM with such settings, the app still somehow outputs an SFC file, but:

- If the Super Metroid ROM is invalid, the resulting file will immediately crash to a black screen.
- If the Metroid ROM is correct but the Link to the Past ROM is invalid, the game will start normally, but attempting any transition from Metroid to Zelda will result in a crash to a black screen.

This is non-intuitive behavior, and if you happen to have wrong ROMs you'll just get garbage output and might be stuck scratching your head trying to figure out what went wrong.

My request here is to validate the user-provided ROMs, for instance, by hashing both files and comparing that against some "known good" hashes (are there several?), perhaps the ROMs that the developers test with, unless there's a better way to do that.

Additionally, I think a note somewhere in the UI specifying the regions for the ROMs that the app is looking for would be quite useful.

**Comment by Vivelin** [comment]
Thank you for the report. We'll add a warning when you select a base game ROM with an unrecognized checksum. This way, you could still continue if you know what you're doing, for example if you have a pre-patched ROM.
