### ISSUE TITLE
"Look at this" for visible locations

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#275]
This should probably go hand-in-hand with #180

**Comment by Vivelin** [comment]
Should it even be an explicit voice command at this point?

Maybe (as an option, perhaps) we could have Tracker auto-track things that are visible. E.g. if you have the map screen open for a second or two, or having an item on-screen (but long enough that it won't happen accidentally).

**Comment by MattEqualsCoder** [comment]
Yeah, I definitely want to have this as an option as well. I'd like to get to a point where we can have a fully automated tracker and you can even disable voice item tracking and stuff which can cause mishaps. While that stuff is great for streams, I could see for a casual playthrough it being a turn off for some folks who just want to chill.

For now, I'll look into the auto "look at this" when I do the medallion check for 8.1. I spun this off into its own because I feel like the visible location checks should probably wait until the redone room based graph logic is implemented since it would end up changing a bunch anyway.
