### ISSUE TITLE
Add alias of "Cutscene Chest" for Misery Mire BK Chest

### ISSUE THREAD

**Issue by CPColin** [Vivelin/SMZ3Randomizer#301]
Betus was wondering today if he could call the Misery Mire Big Key Chest the "Misery Mire Cutscene Chest" when talking to Tracker. I can see a few places where this alias _could_ be added, but I'm not sure which spot is right, so filing it so I don't forget.

**Comment by MattEqualsCoder** [comment]
Should be pretty simple to do. You'll want to create an entry in the sassy profile locations.yml file for the Misery Mire Big Key Chest and put in an extra name. It could also go into the BCU locations.yml file, but I think this is generic enough to be fine in the sassy profile.

**Comment by CPColin** [comment]
Okay, cool. That's what I figured, but then I saw some locations defining alsoKnownAs values and wondered if it needed to be in MiseryMire.cs, too. Will add it to the YAML soon, thanks!

**Comment by Vivelin** [comment]
This name is probably generic enough it could go into the code instead

**Comment by MattEqualsCoder** [comment]
In that case, then it would go into LocationsConfig.cs.

Thinking on this, we should probably remove AlsoKnownAs/AlternateNames for the Location class as it's not really used anywhere. Currently it's only used for creating plandos, but the plando file uses the base location, so I don't know how anyone would get the alternate names anyway. I think in the long run removing would just clean things up a bit.

**Comment by CPColin** [comment]
Lemme see if I can get Visual Studio to behave so I can get the first part done. Then I can see if I can confidently do the second part!

**Comment by CPColin** [comment]
Okay, that oughtta do it!
