### ISSUE TITLE
Revise "Where Should I Go?" Hint

### ISSUE THREAD

**Issue by MattEqualsCoder** [Vivelin/SMZ3Randomizer#323]
Currently when this hint is asked, tracker looks at the available locations with a progression item and gives a random hint off of those. However, this could be a misdirection. It could be something like the wave beam even when the wave beam isn't required for that seed.

It would be good to actually take those possible progression items, then do something like an add a check similar to the hint tiles to find one of the locations where you can't actually beat the game without going there.

**Comment by Vivelin** [comment]
Maybe we should take this one step further and consolidate all the different hint 'algorithms' so we'll no longer have the issue of Tracker saying one thing and in-game hints saying another.

I'll see what I can do. I've been away from all of this too long.

**Comment by MattEqualsCoder** [comment]
Yeah, at this point I'd agree. While I personally don't like the idea of when you ask tracker what's at a location she flat out tells you whether it's mandatory or not as I still argue that's basically a less detailed spoiler, that seems to be what people are expecting.

I wonder if we could swap the order of the hints though. Maybe start by doing super vague item descriptions, then eventually if you continue asking she'll say it's mandatory vs not mandatory?
