### ISSUE TITLE
Add an enum for Location ID's

### ISSUE THREAD

**Issue by CPColin** [Vivelin/SMZ3Randomizer#341]
Currently, each `Location` is defined with a unique ID that's used in places like the hint system and the YAML files. It would be nice to make an enum so all the ID's can be listed in the same place.

It would be great if the YAML files could optionally use the enum values, too, but it's fine if they can't.

Taking this on as an exploratory exercise. I'm not sure yet if it makes sense to do. The idea I'm kicking around is to eventually move away from declaring properties for every `Location` and refer to all of them by ID only. In theory, we could then progress to turning the existing `Room` ID's into another enum and removing the properties for them, too. I figure any eventual graph-based logic we make would be very cluttered if every `Room` had to have a class and a property defined for it.

**Comment by MattEqualsCoder** [comment]
I think enums would be great. I think biggest potential points of concern would be multiworld and tracker saves. But this sounds like a great idea to me.

**Comment by CPColin** [comment]
Oh, good call. I'll have to make sure the enum values still serialize as ints.
