### ISSUE TITLE
Auto-track the dungeon reward in Keysanity mode

### ISSUE THREAD

**Issue by CPColin** [Vivelin/SMZ3Randomizer#357]
PKR noticed during her stream today that when Keysanity is on and we didn't previously know the reward for a dungeon on the way in, we have to tell Tracker to track it manually, after beating the boss. This was tough today because Tracker wasn't immediately hearing the distinction between which pendant it was. Pink suggested that Tracker could look up which reward it was and auto-mark it.

This would also eliminate the need to check your menu after an unknown crystal drops, to see if it's blue or red, for better or worse.

**Comment by MattEqualsCoder** [comment]
Yeah, this is something I've had on my mind for a while. tbh, I'd like to get it to where it can be 100% fully autotracked eventually, though maybe that should be behind settings.
