### ISSUE TITLE
Ganon keeps saying "Silver arrows? What are those?"

### ISSUE THREAD

**Issue by CPColin** [Vivelin/SMZ3Randomizer#401]
Pink pointed out in today's stream that Ganon didn't give a Silver Arrows hint, but instead said, "Silver arrows? What are those?" even though they were in GT somewhere. It looks like that line is only supposed to happen when a plando has removed them from the game.

**Comment by MattEqualsCoder** [comment]
Just looked it up, and it looks like it happened with betus's last run as well. Most likely as issue with pulling out the patches into separate classes.
