### ISSUE TITLE
Tracker Fails to Show Viewed Hints

### ISSUE THREAD

**Issue by doomcup** [Vivelin/SMZ3Randomizer#451]
For some reason, the tracker refuses to show any viewed hints despite interacting with multiple hint tiles. Suspected an errant click hid them, but no clicking anywhere seems to show them again.
![image](https://github.com/Vivelin/SMZ3Randomizer/assets/47144764/845ca64e-7e85-413d-85e0-d06eafce87fd)

**Comment by doomcup** [comment]
Nevermind, it's started working again. 🤷 
![image](https://github.com/Vivelin/SMZ3Randomizer/assets/47144764/79427322-8b2f-4d75-ba72-131cc9aef0e0)

**Comment by MattEqualsCoder** [comment]
@doomcup Ah, I think I can maybe clear this up if you're getting confused about what I'm thinking.

If a hint tile is either for a single location or for the misery mire/turtle rock entrance, it'll either update the marked location list or update the dungeon requirement in the main tracker window, but it won't show up in the viewed hints section. That section is for groups of locations such as caves and dungeons which wouldn't easily fit into the marked locations list or somewhere else. That might explain why Hype Cave shows up, but the hint tile text for waterway, magic bat, and ped don't show up.

Perhaps I should rename the section on the location list "Area Hints" or something to be more explicit.
