### ISSUE TITLE
Invalid TrackerHintStates table -> unable to load tracker completely

### ISSUE THREAD

**Issue by fxbx** [Vivelin/SMZ3Randomizer#459]
Seed & files were created yesterday in app v9.6.1, and after upgrading today to v9.7.0, I was unable to open the tracker associated with it. Exception text from log is attached.

I eventually traced this into the DB storing the tracker saved states, and found the Misery Mire records for the correct TrackerStateID.

Unfortunately I don't have a backup of smz3.db to check how it was originally created yesterday, or before the upgrade took place. If no DB updates would have happened during the app update, something must have changed in the database during tracking in order to cause this.

After editing the two Misery Mire hint tiles to resemble the "The left side of swamp palace" below them (copying over only certain columns), the exception disappeared and I could start everything normally.

I will attempt later to generate seeds with hint tiles to see if this can be re-created.
[logged Exception - Hint location NullRef.txt](https://github.com/Vivelin/SMZ3Randomizer/files/13881626/logged.Exception.-.Hint.location.NullRef.txt)
![nullMire - fixed](https://github.com/Vivelin/SMZ3Randomizer/assets/1474892/29889046-c4b6-4cca-a723-d49a06c60974)
![nullMire](https://github.com/Vivelin/SMZ3Randomizer/assets/1474892/e74ace40-965c-456c-8a90-91841bb6bbe5)

**Comment by MattEqualsCoder** [comment]
Admittedly I'm not sure if it would be advised to upgrade SMZ3 versions in the middle of running a seed, but honestly I'm not aware of anything in the recent version that would have caused this particular issue, which is worrisome as it would possibly mean there may be something more underlying with the hint tiles.

I'll take a look in the next day or two to see if I can replicate and dig into the code to see what might have happened here.

**Comment by MattEqualsCoder** [comment]
Would you maybe be able to right click on the seed in the list and send over the config string? It'll hopefully make it easier when I try to replicate this.

**Comment by fxbx** [comment]
> Would you maybe be able to right click on the seed in the list and send over the config string? It'll hopefully make it easier when I try to replicate this.

pwcAAB+LCAAAAAAAAAp1VU1z2zgM/Ss7OueQOK2T+mbJsZttnHjNdDrTGypBFscUofLDXjWT/74g9WFvPT14JD+Aj+DjA/SWrKDGNRWYzK6vki/YWtDStSOyhZxfSlAWr5KFtPBDoWhIKjRPtPs98mog36PpE+wfwp+ldhexrEI4Q1egST/qg9S55Ggyu7lKHv51qAss1tYL3zRk3JguKl+WChde75D02luZx/I/IxiXkSITGZ7oyIhyVYrYiAaxSGa3YwkcfdBodm2IjtRr1L5PZYYMrAcl1htweYVcrzOek76jKmBhqLFx2xUyDzgUvOxFq3Yke5J6/8yKJ7NuScKlQ+1tj21lXjk0f6WoatIuRKXeKfxGRhXDXmuvnOyRnna8txF5LGIhGwUtmp6d6TYVaXQyP0NixsrLovsfSua3yfX13eTj9OP0U8Sc4zqscIYfXV5GTRty57oIHhlShiKfKAcn+Qod1gy+vQdoJ/OMdCmZ4i3ZGDygdiI3eJw7x84QVDpetx84+oylPOCGjmhSqn905fV7YOkE6GIj3RZ/emnQiiZUmIJSYxJ4nVcbKIaUxxxThHqIf+NrMkdon5nYrgwcWEXhpRviD2Bb/rks3KeRIPZtONN5OFUeU97XOjCv1AyhLxWpImAYuTPQ+FIKqoFZxnv6TgZieOvZY71afewfz+ZFswbWbSBd8hG2VCzA7LdEZ8mPrCs7AINIf/v65N8NGLZ/dHBKZJnwZG0C94dAvu9EHPrrSCY6+WzjXl+5q1x0oyDvqiXscalk08T2HyRWKpS0kGUpc3Yv23TyHntpbKO3oQmXCmwVXdYtHmYO2wS1qJj+N3uIHE7VbNkOVMtf4UjOqVODzmU9123qnSM9YINkomEDd5r1LGgbOaZFhfZxJHTAM5oSi6wCsxuLeaaUflFwsDpz8JKNsyA6SRGAB4UHcGfgFkup1Jy9fEDhYtuc2UuiGQQcVwgNzZpMU40zAZ0hWcy9o8DSwe8jzl3HTxV1FhURu/tmenv/4Srpjn07uZves9YsPUcm/BqcKFBhzqn3N58mHcIezpFdMf0QFf3KS2+m8XVBRy76lvPWRJoLHjU4rUux4vYKozh8WLzubuN/KDNdoHwMHlJ8r8Ps0F6pfgw2cXr1M6wbuqzeAhx3WJcWtud4jjV7ZevDp4T3+arlT4/hQ5SR50E74yPHgXw5SXsJLwPxE2Vfw2TKTMuNrnquuz52gb40qDetgToM257llTzPA52StX0iaxuKfmnCUeLsfP8PL7yIFqcHAAA=

**Comment by fxbx** [comment]
I was just able to recreate the issue in two new seeds, editing the table [TrackerHintStates] after generating these as normal.

If any record where LocationKey IN ('Misery Mire', 'Turtle Rock') has HintState=1, then the tracker will fail to completely load with the reported exception.

MessageBox has text = "There was a problem with loading one or more of the tracker modules. Some tracker functionality may be limited."

**Comment by MattEqualsCoder** [comment]
Ahhh, I bet you it's probably the hints for stating the medallion requirements for Misery Mire and Turtle Rock are breaking on reloading. Those don't have locations associated with them, but it's probably trying to load the locations like the other hint tiles and is failing. That's some good info, and I'll try to get a fix out for it this week!
