### ISSUE TITLE
No Linux Documentation, Unable to Use the Linux Version

### ISSUE THREAD

**Issue by doomcup** [Vivelin/SMZ3Randomizer#470]
I downloaded the latest release for linux, hoping it would be as usable as the windows version was. After installing the required .NET runtime, I was presented with two possibilites as to which executable was the actual randomizer. Attempting to use both only got me an error message saying I needed a rom to continue.

No documentation on github or the cas randomizer site has any information on how to actually use this. I wasn't able to find anything of a GUI or documentation on how to use it on the command line.

Could you add some kind of readme or such on how to actually use this?

EDIT: yes I know it needs a rom. How do I provide it in the console? What are the environment variables I need to set? *How do I use this?*

**Comment by MattEqualsCoder** [comment]
Admittedly, the Linux version is still very much a WIP, and is at the moment a lower priority. You can use it to generate seeds, and it does technically offer command line based auto tracking, but it's very basic. I do plan on making a Linux version with a UI when I find the time, but there are other things on my roadmap first. And, unfortunately there will probably be no voice detection or text to speech as the Microsoft libraries for those don't support Linux, but we'll see if I can find any third party libraries for it.

For the current iteration, I'll try to find some time to write up some basic documentation this weekend, but what it does is when you run it, it'll create a YAML file in the folder that you edit for the settings. You edit that with the rom paths, logic settings, etc.

**Comment by doomcup** [comment]
Ah okay, thanks. I don't envy the amount of work that'll have to go into a linux version of this, but it's appreciated.

**Comment by MattEqualsCoder** [comment]
I will say as well, if you have the ability to run Windows in a virtual machine, what I currently do is have the randomizer and tracker on my Windows VM connect to QUSB2SNES/RetroArch on my host Linux machine. That's how I've been playing since switching to Linux last year.

**Comment by doomcup** [comment]
Thanks for letting me know. I'm no longer running linux on my desktop at the moment, but I could probably test it on my laptop that's still running it.
