### ISSUE TITLE
Starting equipment

### ISSUE THREAD

**Issue by Vivelin** [Vivelin/SMZ3Randomizer#57]
I'd be pretty sweet to be able to select what equipment to start with, e.g. starting with 10 bombs in Zelda.

**Comment by MattEqualsCoder** [comment]
Putting this down for future reference. While Archipelago doesn't support an initial inventory for SMZ3, it does support it for both Z3 and SM (even though VARIA does not unless I'm missing it). We may be able to use that to figure out how to implement starting equipment for SMZ3.
